---
title: "dani-a"
format: html
---

**Article:** [Teamwork Skills: Being an Effective Group Membe](https://uwaterloo.ca/centre-for-teaching-excellence/catalogs/tip-sheets/teamwork-skills-being-effective-group-member) from 'Unversity of Waterloo'

I really enjoyed the focus on skills that not only each team member should have when working as a group but skills the group as a whole should have as well. It starts off with talking about communication skills stating that team members should explain their ideas, express their feelings in a non-offense way, listen to others, ask clarifying questions and encourage other group members. 
Next it talks about how to create a healthy climate as an entire group stating that as a group you should get to know one another, trust one another, demonstrate support for one another, and lastly communicate your opinions respectfully.

Lastly the article mentions skills particularly for the group process and making it as effective as possible. Such skills include agreeing on what needs to be done and how we go about dividing up work, giving and receiving feedback, making a plan, and creating roles for the group.
